version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: okara-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: okara
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - okara-network

  redis:
    image: redis:7.2-alpine
    container_name: okara-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass password
    volumes:
      - redis_data:/data
    networks:
      - okara-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  okara-network:
    driver: bridge