version: '3.8'

services:

  redis:
    image: redis:7.2-alpine
    container_name: okara-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass password
    volumes:
      - redis_data:/data
    networks:
      - okara-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  okara-network:
    driver: bridge